config/routes.rb
YoungWorkers::Application.routes.draw do
  resources :submissions
  devise_for :admins
  resources :contents
  root :to => "home#index"
  match '/about' => 'home#about-us'
  match '/list-of-interviews' => 'home#list'
  match '/apply' => 'submissions#new'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/content.rb
class Content < ActiveRecord::Base
  validates_presence_of :title, :body, :description, :quote
end

app/models/submission.rb
class Submission < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  def bounce
    if admin_signed_in?
      return
    else
      redirect_to root_url
      flash[:error] = "You aren't authorized to view that resource!"
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :bounce, :except => [:show]
  
  def index
    @contents = Content.all(:order => "created_at DESC")
  end
  
  def new
    @content = Content.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content  }
    end
  end
  
  def show
    @content = Content.find(params[:id])
  end

  def edit
    @content = Content.find(params[:id])
  end

  def create
    @content = Content.new(params[:content])
    respond_to do |format|
      if @content.save
        format.html { redirect_to root_url, notice: 'Content was successfully created.' }
        format.json { render json: @content, status: :created, location: @content }
      else
        format.html { render action: "new" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @content = Content.find(params[:id])
    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to root_url, notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @contents = Content.order("created_at DESC").page(params[:page]).per(3)
  end
  
  def show
    @content = Content.find(params[:id])
  end
  
  def list
    @contents = Content.order("title")
  end
  

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
   before_filter :bounce, :except => [:new]  
   
  def index
    @submissions = Submission.order("created_at DESC").page(params[:page]).per(10)
  end
  
  def new
    @submission = Submission.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @submission  }
    end
  end
  
  def edit
    @submission = Submission.find(params[:id])
  end

  def create
    @submission = Submission.new(params[:submission])
    respond_to do |format|
      if @submission.save
        format.html { redirect_to root_url, notice: 'Submission was successfully created.' }
        format.json { render json: @submission, status: :created, location: @submission }
      else
        format.html { render action: "new" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @submission = Submission.find(params[:id])
    respond_to do |format|
      if @submission.update_attributes(params[:submission])
        format.html { redirect_to "/submissions", notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_submission }
    end
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-alert"
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/contents/_form.html.erb
<%= simple_form_for(@content, :html => { :class => "form-horizontal" } ) do |f| %>
<fieldset>
	<%= f.input :title, label: 'Title', placeholder: 'Urologist' %>
	<%= f.input :number, label: 'Interview Number', placeholder: '1, 2, 3...'%>
	<%= f.input :description, placeholder: 'This description appears at the top of the full transcript. (3-4 sentences)', input_html: { class: 'input-xxlarge', rows: '4' } %>
	<%= f.input :quote, label: 'Homepage Teaser', placeholder: 'This text appears on the homepage before the jump to the full transcript. (4-6 sentences)', input_html: { class: 'input-xxlarge', rows: '4' } %>
	<%= f.input :body, placeholder: 'Use <b> tags to bold any interviewer questions. Use <p> tags to enclose paragraphs.', input_html: { class: 'input-xxlarge' } %>
	<%= f.button :submit %>
</fieldset>
<% end %>

app/views/contents/edit.html.erb
<!--body-->
<div class="page-header">
	<h3>Edit "<%= raw @content.title %>"</h3>
</div>
<%= render 'form' %>

app/views/contents/index.html.erb
<div class="page-header">
	<h1>Contents</h1>
</div>
<div class="row-fluid">
	<div class="span6 offset3">
		<table class="table table-hover">
			<% @contents.each do |content| %>	
			<tr>
				<td><%= content.number %>.</td>
				<td><%= raw content.title  %></td>
				<td><%= link_to "Show", url_for(content) %></td>
				<td><%= link_to "Delete", content_path(content), :method => :delete %></td>
				<td><%= link_to "Edit", edit_content_url(content) %></td>
			</tr>
			<% end %>
		</table>
	</div>
	<br>
	<br>
</div>
<br>
<div class="text-center">
	<%= link_to 'Add Content', new_content_url %>
</div>

app/views/contents/new.html.erb
<!--body-->
<div class="page-header">
	<h3>Add New Content</h3><Add New Content</h2>
</div>
<%= render 'form' %>

app/views/contents/show.html.erb
<!-- fb share code -->
<div id="fb-root"></div>
<script>
	( function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id))
				return;
			js = d.createElement(s);
			js.id = id;
			js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk')); 
</script>
<div class="page-header">
	<h3>#<%= @content.number %>, <%= raw @content.title %></h3>
</div>
<!-- header links -->
<div class="pull-right" id "sidebar">
	<p class="text-right">
		<a href="/">HOME</a>
		<br \>
		<a href="/about">ABOUT</a>
		<br \>
		<a href="/list-of-interviews">INTERVIEW INDEX</a>
		<br \>
		<a href="/apply">GET INTERVIEWED!</a>
	</p>
</div>
<!-- body -->
<div class="row-fluid">
	<div class="span6 offset3">
		<p class="lead">
			<%= raw @content.description%>
		</p>
		<div>
			<%= raw @content.body %>
		</div>
		<!-- social media -->
		<div class="text-center">
			<hr \>
			<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
			<script>
				! function(d, s, id) {
					var js, fjs = d.getElementsByTagName(s)[0];
					if (!d.getElementById(id)) {
						js = d.createElement(s);
						js.id = id;
						js.src = "//platform.twitter.com/widgets.js";
						fjs.parentNode.insertBefore(js, fjs);
					}
				}(document, "script", "twitter-wjs");
			</script>
			<div class="fb-like" data-send="false" data-width="450" data-show-faces="false"></div>
		</div>
	</div>
</div>
<br \>
<br \>
<br \>
<br \>

app/views/home/_headerlinks.html.erb
<div class="pull-right">
	<p class="text-right">
		<a href="/">HOME</a>
		<br \>
		<a href="/about">ABOUT</a>
		<br \>
		<a href="/list-of-interviews">INTERVIEW INDEX</a>
		<br \>
		<a href="/apply">GET INTERVIEWED!</a>
	</p>
</div>

app/views/home/about-us.html.erb
<div class="page-header">
	<h3>About</h3>
</div>
<!-- header links -->
<%= render 'headerlinks' %>
<!-- body -->
<div class="row-fluid">
	<div class="span6 offset3">
		<p class="lead">
			Young &amp; Working is an oral history project that focuses on the stories of workers under 35 years old.
		</p>
		<p>
			In 1974, Studs Terkel published <i>Working: People Talk About What They Do All Day and How They Feel About What They Do</i>,
			a collection of oral histories of Americans on the job.  Since the book's publication, the U.S. working world has changed
			dramatically.  Manufacturing jobs now make up a much smaller share of the employment market, while service industry jobs have
			become more and more numerous.  Unpaid internships, freelance, and part-time work have replaced entry-level positions in many 
			white-collar fields.  The career-long, sustainably-paid job is more or less extinct.
		</p>
		<p>
			Not only do young workers today face a different job landscape than previous generations, they face a challenging economic
			climate.  Wages are stagnant, and under- and un-employment are common. Blue-collar jobs have been <a href="http://www.nytimes.com/2008/01/16/us/16ohio.html?pagewanted=all&_r=0"> disappearing for years</a>. Though a college degree is all but necessary to secure
			a white-collar position, undergraduate education no longer has any real weight in the job market.  Meanwhile, the cost of attending college has
			<a href="http://www.bloomberg.com/news/2012-08-15/cost-of-college-degree-in-u-s-soars-12-fold-chart-of-the-day.html">increased 1,120&#37; since
			1978.</a>
		</p>
		<p>
			Young &amp; Working is interested in the experiences of young workers.  We'd like to hear from you if you're younger than 35 and
			working a job (we count things like independent projects and parenthood!).  We're seeking diverse contributors from all backgrounds,
			and we particularly welcome the voices of contingent workers, queer workers, undocumented workers, and workers of color.
		</p>
		<p>
			If you'd like to add your story to our collection, please <a href="/apply">get in touch</a>.  We also love <a href="mailto:youngandworking@gmail.com"> email</a>.
		</p>
	</div>
</div>

app/views/home/apply.html.erb
<div class="page-header">
	<h3>We Like You, Too!</h3>
</div>
<!-- header links -->
<div class="pull-right">
	<p class="text-right">
		<a href="/">HOME</a>
		<br \>
		<a href="/about-us">ABOUT</a>
		<br \>
		<a href="/list-of-interviews">INTERVIEW INDEX</a>
		<br \>
		<a href="/apply">TELL YOUR STORY!</a>
	</p>
</div>
<!-- body -->

app/views/home/index.html.erb
<!-- body -->
<!-- header links -->
<div id="homeheader" style="padding-top:50px">
	<%= render 'headerlinks' %>
</div>
<%= image_tag 'young and working.png', :class => 'logo' %>
<!-- content -->
<div class="row-fluid">
	<div class="span6 offset3">
		<table class="table">
			<tr>
				<% @contents.each do |content| %>
				<td>
				<br />
				<div class="today">
					<div id="<%= content.created_at.strftime("%d-%m-%Y") %>">
						<span class="badge badge-info" > new! </span>
					</div>
				</div>
				<br />
				<p>
					<small>#<%= content.number%>, <%= content.title.upcase %></small>
				</p>
				<p class="lead">
					"<%= raw content.quote %>"
				</p>
				<div class="pull-right">
					<p>
						<small><%= link_to 'READ MORE', content_path(content.id) %></small>
					</p>
				</div></td>
			</tr>
			<% end %>
		</table>
		<div class="pull-right">
			<%= paginate @contents %>
		</div>
	</div>
</div>

app/views/home/list.html.erb
<div class="page-header">
	<h3>Interviews</h3>
</div>
<!-- header links -->
<%= render 'headerlinks' %>
<!-- body -->
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<% @contents.each do |content| %>
			<p>
				<a href="/contents/<%= content.id %>"><%= raw content.title  %></a> (<%= content.created_at.strftime('%B %e, %Y') %>)
			</p>

			<% end %>
		</div>
	</div>
</div>

app/views/layouts/_flash_messages.html.erb
<% unless flash.blank? %>
<% flash.each do |key, value| %>
<div class="row-fluid">
	<div class="span6 offset3">
		<div class="<%= flash_class(key) %> fade in">
			<a href="#" data-dismiss="alert" class="close">×</a>
			<%= value %>
		</div>
	</div>
</div>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- We're running on RoR & Bootstrap! -->
<html>
	<head>
		<title>Young &amp; Working</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<link href='http://fonts.googleapis.com/css?family=Cantarell' rel='stylesheet' type='text/css'>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= favicon_link_tag 'favicon (1).ico' %>
	</head>
	<body>
		<div class="container">
			<div class="pull-right">
				<% if admin_signed_in? %>
				Logged in as <%= current_admin.email %>&nbsp;&nbsp;||&nbsp;&nbsp;
				<%= link_to('Manage Content', contents_path) %> &nbsp;&nbsp;||&nbsp;&nbsp;
				<%= link_to('Manage Submissions', submissions_path) %>&nbsp;&nbsp;||&nbsp;&nbsp;
				<%= link_to('Logout', destroy_admin_session_path, :method => :delete ) %>
				<% end %>
			</div>
			<!-- alerts -->
			<%= render 'layouts/flash_messages'  %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/submissions/_form.html.erb
<%= simple_form_for(@submission, :html => { :class => "form-horizontal" } ) do |f| %>
<fieldset>
	<%= f.input :name, placeholder: 'We\'ll keep your real name confidential, or you can use an alias.', input_html: { class: 'input-xxlarge', rows: '4' } %>
	<%= f.input :email, required: true %>
	<%= f.input :age,  collection: 10..35, hint: 'Please be 35 or younger; we’re down with all workers, but this project has a specific scope.' %>
	<%= f.input :job, placeholder: 'Give us a sense of your current and/or past work in a few sentences.', input_html: { class: 'input-xxlarge', rows: '6' }%>
	<%= f.input :demographic, label: 'Demographic info (optional)', required: false, placeholder: 'Any info you wish to provide about your race, gender, sexual preference, family background, etc. is helpful to us in ensuring the diversity of the project.', input_html: { class: 'input-xxlarge', rows: '6' } %>
	<%= f.input :location, collection: ["New York", "San Francisco"] %>
	<%= f.button :submit %>
</fieldset>
<% end %>

app/views/submissions/edit.html.erb
<!-- body -->
<div class="page-header">
	<h1>Update Submission for <%= @submission.name %></h1>
</div>
<!-- form -->
<%= simple_form_for(@submission, :html => { :class => "form-horizontal" } ) do |f| %>
<fieldset>
	<%= f.input :status, collection: ["Declined", "Waitlisted", "Sara", "Senait", "Published"], input_html: {class: 'status'} %>
	<%= f.input :notes, placeholder: 'Updates on status of submission go here (please enter notes any time you change status of submission).', input_html: { class: 'input-xxlarge', rows: '6' } %>
	<%= f.button :submit %>
</fieldset>
<% end %>

app/views/submissions/index.html.erb
<div class="page-header">
	<h1>Submissions</h1>
</div>
<div class="row-fluid">
	<%= paginate @submissions %>
	<table class="table table-hover">
		<% @submissions.each do |submission| %>
		<tr>
			<td>
			<p class="lead">
				<a href="/submissions/<%= submission.id %>/edit"><%= submission.name  %></a>&nbsp;&nbsp;<span class="<%= submission.status  %>"><%= submission.status  %></span>
			<p>
				<b>Email: </b><%= submission.email  %>
			</p>
			<p>
				<b>Age: </b><%= submission.age  %>
			</p>
			<p>
				<b>Location: </b><%= submission.location  %>
			</p>
			<p>
				<b>Job Summary: </b><%= submission.job  %>
			</p>
			<p></td>
			<td>
				<b>Demographic info: </b><%= submission.demographic  %>
			</p>
			<p>
				<b>Admin Notes: </b><span class="text-error"><%= submission.notes  %></span>
			</p>
			</td>
		</tr>
		<% end %>
	</table>
	<%= paginate @submissions %>
</div>

app/views/submissions/new.html.erb
<div class="page-header">
	<h3>Shucks. We Like You, Too!</h3>
</div>
<!-- header links -->
<div class="pull-right">
	<p class="text-right">
		<a href="/">HOME</a>
		<br \>
		<a href="/about">ABOUT</a>
		<br \>
		<a href="/list-of-interviews">INTERVIEW INDEX</a>
		<br \>
		<a href="/apply">GET INTERVIEWED!</a>
	</p>
</div>
<!-- body -->
<p class="lead">
	Thanks for your interest in collaborating with us!  Please complete the form below, and we'll contact you within
	a few weeks if we're able to interview you.
</p>
<p class="text-warning">
	Please note that Young &amp; Working is currently based in New York and San Francisco and prefers to interview
	collaborators in person.  Shoot us an <a href="mailto:youngandworking@gmail.com">email</a> if you're somewhere else,
	or watch the homepage; we'll announce when we're traveling.
</p>
<br \>
<br \>
<!-- form -->
<%= simple_form_for(@submission, :html => { :class => "form-horizontal" } ) do |f| %>
<fieldset>
	<%= f.input :name, placeholder: 'We\'ll keep your real name confidential, or you can use an alias.', input_html: { class: 'input-xxlarge', rows: '4' } %>
	<%= f.input :email, required: true %>
	<%= f.input :age,  collection: 10..35, hint: 'Please be 35 or younger; we’re down with all workers, but this project has a specific scope.' %>
	<%= f.input :job, placeholder: 'Give us a sense of your current and/or past work in a few sentences.', input_html: { class: 'input-xxlarge', rows: '6' }%>
	<%= f.input :demographic, label: 'Demographic info (optional)', required: false, placeholder: 'Any info you wish to provide about your race, gender, sexual preference, family background, etc. is helpful to us in ensuring the diversity of the project.', input_html: { class: 'input-xxlarge', rows: '6' } %>
	<%= f.input :location, collection: ["New York", "San Francisco"] %>
	<%= f.button :submit %>
</fieldset>
<% end %>